name: AsDimo CI/CD

on:
  push:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: asDimoWebApp

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci
      - run: npm run build

  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: asDimoBackend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci

  deploy:
    needs: [frontend, backend]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Backend
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ process.env.SERVER_HOST }}
          username: ${{ process.env.SERVER_USER }}
          key: ${{ process.env.SERVER_SSH_KEY }}
          script: |
            cd ~/public_html/dev/asDimo

            git pull origin main

            cd asDimoBackend
            npm install

            npx pm2 restart asdimo-api || npx pm2 start server.js --name asdimo-api